myapp/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
app_name = 'my_project'
urlpatterns = [
    
    path('' ,views.home),
    path('download' ,views.download),
    
    path('download/<resolution>' ,views.downloaded, name="downloaded"),
    path('download/' ,views.downloaded_audio, name="downloaded_audio"),
    path('download/done' ,views.done),
   
]

youdown/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include("myapp.urls")),

    # url(r'^media/ ( ?P<path>.* ) $',serve,{'document_root':settings MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py

from django.shortcuts import render, redirect
import os
from pytube import YouTube
from django.http import FileResponse
from io import BytesIO
from datetime import datetime


def home(request):

    return render(request, "index.html")

def done(request):

    return render(request, "done.html")
# Create your views here.


def download(request):
		try:
			global url
			url = request.GET.get('myurl')
			resolutions = []
			if request.method == 'GET' and url is not None:
				obj = YouTube(url)
				thumb = obj.thumbnail_url
				title = obj.title
				streamAll = obj.streams.all()
				for i in streamAll:
					resolutions.append(i.resolution)
				resolutions = list(dict.fromkeys(resolutions))
				resolutions.remove(None)
				# print(resolutions, thumb)
				return render(request, "download.html", {'res': resolutions, 'thum': thumb, 'title': title})
			return redirect('/')
		except Exception as e:
			raise e	


# def downloaded(request,resolution):
# 	global url 
# 	homedir=os.path.expanduser("~")
# 	dirs=homedir+'/Downloads'
# 	if request.method == 'POST':
		
	
# 		YouTube(url).streams.filter(res=resolution).first().download(dirs)
# 		# return FileResponse(open(YouTube(url).streams.first().download(skip_existing=True),'rb'))
# 		return render(request, "done.html")

def downloaded(request,resolution):
			try:	
				yt=YouTube(url)
				
				time = datetime.now().strftime("%H:%M")
				title=yt.title
				stream=yt.streams.filter(res=resolution).first()
				data=stream.download()

				path=os.path.normpath(data)
				
				with open(path,'rb') as f:
					byteData=f.read()
				os.remove(data)
				return FileResponse(BytesIO(byteData),filename=title+' '+resolution+' ' +time+' youDown.mp4',as_attachment=True,content_type='video/mp4')
			except Exception as e:
				raise e	

def downloaded_audio(request):
		try:
			yt=YouTube(url)
			
			time = datetime.now().strftime("%H:%M")
			title=yt.title
			stream=yt.streams.filter(only_audio=True).first()
			data=stream.download()
			path=os.path.normpath(data)
			with open(path,'rb') as f:
				byteData=f.read()
			os.remove(data)
			return FileResponse(BytesIO(byteData),filename=title +' '+time+' youDown.mp3',as_attachment=True,content_type='audio/mpeg')
		except Exception as e:
			raise e		
		# return redirect (request, "done.html")

templates/done.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- CSS only -->
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    /> -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="icon" type="image/png" href="{ % static 'images/logo.png' % }" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>youDown</title>
  </head>

  <body class="bg-black">
    {% include "navbar.html" %}

    <!-- hero section -->

    <div
      class="hero rounded m-auto mt-4 bg-gradient-to-r from-violet-500 to-green-500"
    >
      <!-- <h1 class="text-center text-4xl font-bold pt-8 p-3">Youtube Video & Audio Downloader</h1> -->
      <form method="get" action="download">
        <div class="flex flex-wrap p-4 py-20 justify-center item-center w-full">
          <div class="mx-3">
            <input
              placeholder="Paste link Here ..."
              name="myurl"
              required
              class="border-slate-200 drop-shadow-2xl m-3 w-45 md:w-96 rounded text-xl p-2 placeholder-slate-400 contrast-more:border-slate-400 contrast-more:placeholder-slate-500"
            />
          </div>
          <div>
            <button
              class="py-2 m-3 px-4 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
              type="submit"
            >
              Search
            </button>
          </div>
        </div>
      </form>
    </div>

    <h1 class="text-center text-white text-xl md:text-4xl font-bold p-3">
      Downloading is Compleated 🎉
    </h1>
   
    
    {% include "footer.html" %}

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'javaScript/app.js' %}"></script>
  </body>
</html>

templates/download.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- CSS only -->
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    /> -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="icon" type="image/png" href="{ % static 'images/logo.png' % }" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>youDown</title>
  </head>

  <body class="bg-black">
    {% include "navbar.html" %}

    <!-- hero section -->

    <div
      class="hero rounded w-full bg-gradient-to-r from-violet-500 to-green-500"
    >
      <!-- <h1 class="text-center text-4xl font-bold pt-8 p-3">Youtube Video & Audio Downloader</h1> -->
      <form method="get" action="download">
        <div class="flex flex-wrap p-4 py-20 justify-center item-center w-full">
          <div class="mx-3">
            <input
              placeholder="Paste link Here ..."
              name="myurl"
              required
              class="border-slate-200 drop-shadow-2xl m-3 w-56 md:w-96 rounded text-xl p-2 placeholder-slate-400 contrast-more:border-slate-400 contrast-more:placeholder-slate-500"
            />
          </div>
          <div>
            <button
              class="py-2 m-3 px-4 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
              type="submit"
            >
              Search
            </button>
          </div>
        </div>
      </form>
    </div>

    <h1 class="text-center text-white text-xl md:text-4xl font-bold p-3">
      Download is ready...
    </h1>
    <img src="{{thum}}" class="m-auto w-52 md:w-60" alt="thumbnail" srcset="" />
    <h1
      class="text-center md:mx-48 text-white text-xl md:text-2xl font-bold p-3"
    >
      {{title}}
    </h1>

    <div class="overflow-x-auto px-auto relative ">
      
        <table
          class="w-1/3 mt-4 m-auto px-auto text-sm text-left text-gray-500 dark:text-gray-400"
        >
          <thead
            class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
          >
            <tr>
              <th scope="col" colspan="2" class="py-3 px-6">Video </th>
              <th scope="col"  class="py-3 px-6">  Audio </th>
              <!-- <th scope="col" class="py-3 px-6">
                      
                  </th> -->
            </tr>
          </thead>
          <tbody>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <td colspan="2"></td>

              <td class="py-4 px-6" rowspan="10">
                
                <form action="{% url 'my_project:downloaded_audio'%}" method="post">
                  {% csrf_token %}
                  <button
                  class="py-1 px-3 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
                  type="submit"
                  
                  >
                  Download Audio
                </button>
              </form>
            </td>
          </tr>
            {% for i in res %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th
                scope="row"
                class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
              >
                {{i}}
              </th>
              <td class="py-4 px-6">
                <form
                  action="{% url 'my_project:downloaded' i %}"
                  method="post"
                >
                  {% csrf_token %}
                  <button
                    class="py-1 px-3 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
                    type="submit"
                  >
                    Download
                  </button>
                </form>
              </td>
            </tr>
            {% endfor %}
           
          </tbody>
        </table>
      
      <!-- <div>
        <form action="{% url 'my_project:downloaded_audio'%}" method="post">
          {% csrf_token %}
          <button
            class="py-1 px-3 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
            type="submit"
          >
            Download Audio
          </button>
        </form>
      </div> -->
    </div>
    
    {% include "footer.html" %}

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'javaScript/app.js' %}"></script>
  </body>
</html>

templates/footer.html
<footer class="text-center text-white bg-gray-800 mt-5" >
	<div class="container pt-9">
		<div class="flex justify-center mb-9">
			
			<a href="https://www.linkedin.com/in/raj-pawar-798ab6203" target="_blank" class="mr-9 text-white">
			  <svg
				aria-hidden="true"
				focusable="false"
				data-prefix="fab"
				data-icon="linkedin-in"
				class="svg-inline--fa fa-linkedin-in w-3.5"
				role="img"
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 448 512"
			  >
				<path
				  fill="currentColor"
				  d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"
				></path>
			  </svg>
			</a>
		
		<a href="mailto:rajm.pawar7038@gmail.com" target="_blank" class="mr-9 text-white">
		  <svg
			aria-hidden="true"
			focusable="false"
			data-prefix="fab"
			data-icon="google"
			class="svg-inline--fa fa-google w-3.5"
			role="img"
			xmlns="http://www.w3.org/2000/svg"
			viewBox="0 0 488 512"
		  >
			<path
			  fill="currentColor"
			  d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"
			></path>
		  </svg>
		</a>
		<a href="https://www.instagram.com/mr_curious_raj/" target="_blank" class="mr-9 text-white">
		  <svg
			aria-hidden="true"
			focusable="false"
			data-prefix="fab"
			data-icon="instagram"
			class="svg-inline--fa fa-instagram w-3.5"
			role="img"
			xmlns="http://www.w3.org/2000/svg"
			viewBox="0 0 448 512"
		  >
			<path
			  fill="currentColor"
			  d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
			></path>
		  </svg>
		</a>
		<a href="https://github.com/rajPawarRmp" target="_blank" class="text-white">
		  <svg
			aria-hidden="true"
			focusable="false"
			data-prefix="fab"
			data-icon="github"
			class="svg-inline--fa fa-github w-4"
			role="img"
			xmlns="http://www.w3.org/2000/svg"
			viewBox="0 0 496 512"
		  >
			<path
			  fill="currentColor"
			  d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
			></path>
		  </svg>
		</a>
	  </div>
	</div>
  
	<div class="text-center text-white p-4" style="background-color: rgba(0, 0, 0, 0.2);">
	  © 2022 Copyright:
	  <a class="text-white" href="/">Developed By Raj</a>
	</div>
  </footer>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="icon" type="image/png" href="{ % static 'images/logo.png' % }" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>youDown</title>
  </head>

  <body class="bg-black">
    {% include "navbar.html" %}

    <!-- hero section -->

    <div
      class="hero rounded w-full    bg-gradient-to-r from-violet-500 to-fuchsia-500"
    >
      <h1 class="text-center text-4xl font-bold pt-8 p-3">
        Youtube Video & Audio Downloader
      </h1>
      <form method="get" action="download">
        <div class="flex flex-wrap p-4 py-20 justify-center item-center w-full">
          <div class="mx-3">
            <input
              placeholder="Paste link Here ..."
              name="myurl"
              required
              class="border-slate-200 drop-shadow-2xl m-3 w-56 md:w-96 rounded text-xl p-2 placeholder-slate-400 contrast-more:border-slate-400 contrast-more:placeholder-slate-500"
            />
          </div>
          <div>
            <button
              class="py-2 m-3 px-4 drop-shadow-2xl bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 duration-500"
              type="submit"
            >
              Search
            </button>
          </div>
        </div>
      </form>

      <div class="flex flex-wrap justify-center">
        
        
<div class="w-72 my-3 mx-2 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
  
  <div class="p-5 ">
      <a href="#">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Copy Link Of The Video</h5>
      </a>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Go To <a href="https://www.youtube.com/" class="font-bold">YouTube🔗</a> or Open YouTube app and Copy Video Link.</p>
     
  </div>
</div>

        
<div class="w-72 my-3 mx-2 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
 
  <div class="p-5">
      <a href="#">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Paste Link </h5>
      </a>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Paste the Link in Search Box and Hit Search Button.</p>
     
  </div>
</div>

        
<div class="w-72 my-3 mx-2 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
 
  <div class="p-5">
      <a href="#">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Download </h5>
      </a>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Choose Desired Video Quality and Format For Downloading Your Video.</p>
     
  </div>
</div>

      </div>

      {% include "footer.html" %}
    <!-- <div class="loader"></div> -->

    <script src="{% static 'javaScript/app.js' %}"></script>
  </body>
</html>

templates/navbar.html
<nav
class="p-2  bg-gray-800 shadow md:flex md:items-center text-white md:justify-between"
>
<div class="flex ml-10 justify-between items-center">
  <a
	class="text-3xl font-bold hover:text-4xl duration-1000 item-center cursor-pointer inline-flex"
  >
	<span class=""><i class="fa-solid fa-circle-down"></i></span>
	<span class="text-white">you</span>
	<span class="text-red-400">Down</span>
  </a>

  <span class="text-3xl cursor-pointer mx-2 md:hidden block">
	<ion-icon name="menu" onclick="Menu(this)"></ion-icon>
  </span>
</div>

<ul
  class="md:flex text-white md:items-center  md:z-auto z-40 md:static absolute bg-white md:bg-gray-800 text-black md:text-white w-full left-0 md:w-auto md:py-0 md:pl-0 pl-7 md:opacity-100 opacity-0 top-[-400px] transition-all ease-in duration-500"
>
  <li class="mx-4 md:my-0 hover:bg-yellow-200 duration-1000 rounded py-3">
	<a href="/" class="text-xl hover:text-black">Home</a>
  </li>
  <li class="mx-4 md:my-0 hover:bg-yellow-200 duration-1000 rounded py-3">
	<a href="https://www.youtube.com/" class="text-xl hover:text-black" target="_blank">YouTube</a>
  </li>
  <li class="mx-4 md:my-0 hover:bg-yellow-200 duration-1000 rounded py-3">
	<a href="#" class="text-xl hover:text-black">Help</a>
  </li>
  <li class="mx-4 md:my-0 hover:bg-yellow-200 duration-1000 rounded py-3">
	<a href="#" class="text-xl hover:text-black">AboutUs</a>
  </li>

  <!-- <h2 class=""></h2> -->
</ul>
</nav>